### ISSUE TITLE
Alteração da proposta

### ISSUE THREAD

**Issue by sergiopetrovcic** [SergioMacedo15/ProjetoIntegrador#2]
Devido à alteração de tema, faça as devidas alterações na sua proposta.

**Comment by SergioMacedo15** [comment]
Terei uma reunião com o Tiago Drummond hoje para definir a proposta que vai ser entregue para o desenvolvimento e em paralelo já altero a proposta aqui.

**Comment by SergioMacedo15** [comment]
feito, adicionado na wiki
